[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
fs_permissions = [{access = "read", path = "./out"}, {access = "read-write", path = "./deployments"}]
ignored_error_codes = ["license", "unused-return", "unused-param"]
verbosity = 3
optimizer = true
optimizer_runs = 200
gas_limit = 10737418240
via-ir = true

[rpc_endpoints]
localhost = "http://localhost:8545"
base = "https://mainnet.base.org"

[etherscan]
unknownchain = { key = "ABCDEFG", url = "https://<etherscan-api-url-for-that-chain>" }

[fuzz]
runs = 1024
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 1000
depth = 50
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_run_limit =  5000
show_metrics = true

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
sort_imports = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
